# https://forum.affinity.serif.com/index.php?/topic/182758-affinity-suite-v204-on-linux-wine/
- name: install affinity wine dependencies
  when: ansible_os_family == "Debian"
  apt: name={{ item }} state=latest update_cache=yes
  loop:
    [
      "flex",
      "bison",
      "gcc-multilib",
      "g++-multilib"
    ]
  become: true

- name: clone affinity wine config
  when: ansible_os_family == "Debian"
  shell: >
    git clone https://gitlab.winehq.org/ElementalWarrior/wine.git ElementalWarrior-wine ~/work/src/gitlab.com/ElementalWarrior/wine
    cd ~/work/src/gitlab.com/ElementalWarrior/wine/
    mkdir wine32-build/ wine64-build/ wine-install/
  become: true

- name: install affinity wine config
  when: ansible_os_family == "Debian"
  shell: >
    cd $(pwd)/wine64-build
    $(pwd)/../configure --prefix=$(pwd)/../wine-install --enable-win64
    # cd $(pwd)/../wine32-build
    # PKG_CONFIG_PATH="/usr/lib32/pkgconfig $(pwd)/../configure --with-wine64=$(pwd)/../wine64-build --prefix=$(pwd)/../wine-install" && make
    make install
  become: true

- name: install rum
  when: ansible_os_family == "Debian"
  shell: >
    git clone https://gitlab.com/xkero/rum
    sudo cp ./rum/rum /bin/rum
  become: true

- name: copy affinity wine version
  when: ansible_os_family == "Debian"
  shell: >
    sudo mkdir /opt/wines
    sudo cp -r ~/work/src/gitlab.com/ElementalWarrior/wine/wine-install/ /opt/wines/ElementalWarrior-8.3

    git clone https://gitlab.com/xkero/rum
    sudo cp ./rum/rum /bin/rum
  become: true

- name: install affinity wine windows dependencies
  when: ansible_os_family == "Debian"
  shell: >
    rum ElementalWarrior-8.3 "$HOME/.WineAffinity" winetricks dotnet48 corefonts
    rum ElementalWarrior-8.3 "$HOME/.WineAffinity" wine winecfg -v win11
    #
    # need folder C:/Windows/System32/WinMetadata
    # should be copied into your prefix in the same place PREFIX/drive_c/Windows/System32/WinMetadata
    #
    # need to change the installer path
    # rum ElementalWarrior-8.3 "$HOME/.WineAffinity" wine "PATH-TO-INSTALLER-msi-2.0.4.exe"
    #
    # to run...
    # rum ElementalWarrior-8.3 "$HOME/.WineAffinity" wine "$HOME/.WineAffinity/drive_c/Program Files/Affinity/Designer 2/Designer.exe
    # rum ElementalWarrior-8.3 "$HOME/.WineAffinity" wine "$HOME/.WineAffinity/drive_c/Program Files/Affinity/Photo 2/Photo.exe
    # rum ElementalWarrior-8.3 "$HOME/.WineAffinity" wine "$HOME/.WineAffinity/drive_c/Program Files/Affinity/Publisher 2/Publisher.exe
    #
    # to run with vulkan (if visual glitches)
    # rum ElementalWarrior-8.3 "$HOME/.WineAffinity" winetricks renderer=vulkan
    # to swap back to gl
    # rum ElementalWarrior-8.3 "/home/USER/.WineAffinity" winetricks renderer=gl
  become: true
