- name: install alacritty packages
  when: ansible_os_family == "Debian"
  apt: name={{ item }} state=latest update_cache=yes
  loop: ["alacritty"]
  become: true

- name: ensure config alacritty directory exists
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.config/alacritty"
    state: directory
    mode: "0755"

- name: setup alacritty
  template: src=../templates/alacritty.toml dest="{{ ansible_env.HOME }}/.config/alacritty/alacritty.toml"
