# Linux related
- name: install alacritty packages
  when: ansible_os_family == "Debian"
  apt: name={{ item }} state=latest update_cache=yes
  loop: ["alacritty"]
  become: true

- name: ensure config alacritty directory exists
  when: ansible_os_family == "Debian"
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.config/alacritty"
    state: directory
    mode: "0755"

- name: setup alacritty
  when: ansible_os_family == "Debian"
  template: src=../templates/alacritty.toml dest="{{ ansible_env.HOME }}/.config/alacritty/alacritty.toml"

- name: setup alacritty theme
  when: ansible_os_family == "Debian"
  template: src=../templates/alacritty_catppuccin.toml dest="{{ ansible_env.HOME }}/.config/alacritty/catppuccin-mocha.toml"

- name: setup alacritty theme modification
  when: ansible_os_family == "Debian"
  template: src=../templates/alacritty_catppuccin_mod.toml dest="{{ ansible_env.HOME }}/.config/alacritty/catppuccin-mocha-mod.toml"
