- name: remove pipewire example session
  when: ansible_os_family == "Debian"
  shell: apt remove -y pipewire-media-session
  become: true

# https://trendoceans.com/enable-pipewire-and-disable-pulseaudio-in-ubuntu/
- name: install pipewire
  when: ansible_os_family == "Debian"
  apt: name={{ item }} state=latest update_cache=yes
  loop:
    [
      "pipewire",
      "pipewire-audio-client-libraries",
      "pipewire-bin",
      "pipewire-pulse",
      "libspa-0.2-bluetooth",
      "libspa-0.2-jack",
      "gstreamer1.0-pipewire",
      "wireplumber",
      "libpipewire-0.3-{0,dev,modules} libspa-0.2-{bluetooth,dev,jack,modules} pipewire{,-{audio-client-libraries,pulse,bin,tests}}",
      "wireplumber gir1.2-wp-0.4 libwireplumber-0.4-{0,dev}"
    ]
  become: true

- name: change to pipewire
  when: ansible_os_family == "Debian"
  shell: >
    systemctl --user --now disable pulseaudio.{socket,service}
    systemctl --user mask pulseaudio
    sudo cp -vRa /usr/share/pipewire /etc/
    systemctl --user --now enable pipewire{,-pulse}.{socket,service}
  become: true

- name: install Audacity
  when: ansible_os_family == "Debian"
  shell: flatpak install flathub org.audacityteam.Audacity -y
  become: true

# - name: install Easy Effects
#   when: ansible_os_family == "Debian"
#   shell: flatpak install flathub com.github.wwmm.easyeffects -y
#   become: true
#
# - name: configure Easy Effects
#   when: ansible_os_family == "Debian"
#   shell: flatpak permission-reset com.github.wwmm.easyeffects
#   become: true

# - name: install qpwgraph
#   when: ansible_os_family == "Debian"
#   shell: flatpak install flathub org.rncbc.qpwgraph -y
#   become: true

- name: install carla
  when: ansible_os_family == "Debian"
  shell: mkdir -p {{ ansible_env.HOME }}/Apps && rm -rf {{ ansible_env.HOME }}/Apps/Carla* && wget -P {{ ansible_env.HOME }}/Apps/ https://github.com/falkTX/Carla/releases/download/v2.2.0/Carla_2.2.0-linux64.tar.xz
# TODO: need to untar
