- name: copy profile configurations
  template: src=../templates/dev/profile dest="{{ ~ | expanduser  }}/.profile"

- name: copy userrc configurations
  template: src=../templates/dev/userrc dest="{{ ~ | expanduser  }}/.userrc"

- name: copy gitconfig configurations
  template: src=../templates/dev/gitconfig dest="{{ ~ | expanduser  }}/.gitconfig"

- name: set github work folder
  shell: mkdir -p {{ ~ | expanduser  }}/work/src/github.com
  become: true

- name: set local work folder
  shell: mkdir -p {{ ~ | expanduser  }}/work/src/local
  become: true
