# TODO: need the ssh key inside first... need to figure a way to pass it
#       as is, the private repos wont work

- name: generate an OpenSSH keypair with the default values (4096 bits, rsa)
  community.crypto.openssh_keypair:
    path: "{{ ansible_env.HOME }}/.ssh/id_rsa"

- name: copy profile configurations
  template: src=../templates/cli/profile dest="{{ ansible_env.HOME }}/.profile"

- name: copy gitconfig configurations
  template: src=../templates/cli/gitconfig dest="{{ ansible_env.HOME }}/.gitconfig"

- name: copy terminal configurations
  git:
    repo: git@github.com:iamajoe/terminal_config.git
    dest: "{{ansible_env.HOME}}/.config/terminal"
    accept_hostkey: true
    force: true
  environment:
    GIT_TERMINAL_PROMPT: false
    GIT_SSL_NO_VERIFY: true
  # shell: git clone --depth 1 git@github.com:iamajoe/terminal_config.git ~/.config/terminal

- name: copy tmux configurations
  template: src=../templates/cli/tmux.conf dest="{{ ansible_env.HOME  }}/.tmux.conf"

- name: copy neovim configurations
  git:
    repo: https://github.com/iamajoe/nvim
    dest: "{{ansible_env.HOME}}/.config/nvim"
    accept_hostkey: true
    force: true
  environment:
    GIT_TERMINAL_PROMPT: false
    GIT_SSL_NO_VERIFY: true
  # shell: git clone --depth 1 https://github.com/iamajoe/nvim ~/.config/nvim
