# Linux related
- name: Add Docker GPG apt Key
  when: ansible_os_family == "Debian"
  become: true
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  when: ansible_os_family == "Debian"
  become: true
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
    state: present

- name: Update apt and install docker-ce
  when: ansible_os_family == "Debian"
  become: true
  apt: update_cache=yes name=docker-ce state=latest

- name: Permissions (group)
  when: ansible_os_family == "Debian"
  shell: groupadd docker || true
  become: true

- name: Permissions (user)
  when: ansible_os_family == "Debian"
  shell: usermod -aG docker {{ ansible_ssh_user }}
  become: true

- name: Enable boot (docker)
  when: ansible_os_family == "Debian"
  shell: systemctl enable docker.service
  become: true

- name: Enable boot (containerd)
  when: ansible_os_family == "Debian"
  shell: systemctl enable containerd.service
  become: true

- name: Permissions (socket)
  when: ansible_os_family == "Debian"
  shell: chmod 666 /var/run/docker.sock
  become: true
