- name: install fish packages
  when: ansible_os_family == "Debian"
  apt: name={{ item }} state=latest update_cache=yes
  loop: ["fish"]
  become: true

- name: ensure config fish directory exists
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.config/fish"
    state: directory
    mode: "0755"

- name: setup fish
  template: src=../templates/config_fish.fish dest="{{ ansible_env.HOME }}/.config/fish/config.fish"
