# Linux related
- name: install required system packages
  when: ansible_os_family == "Debian"
  apt: name={{ item }} state=latest update_cache=yes
  loop: ["fontconfig"]
  become: true

- name: download nerd font
  when: ansible_os_family == "Debian"
  ansible.builtin.get_url:
    url: "https://github.com/ryanoasis/nerd-fonts/releases/download/v3.3.0/Noto.tar.xz"
    dest: "/tmp/notonerd330.tar.gz"
    mode: "0644"

- name: ensure noto font folder
  when: ansible_os_family == "Debian"
  ansible.builtin.file:
    path: "/usr/share/fonts/noto"
    state: directory
    mode: "0755"
  become: yes

- name: extract and install nerd font
  when: ansible_os_family == "Debian"
  ansible.builtin.unarchive:
    src: "/tmp/notonerd330.tar.gz"
    dest: "/usr/share/fonts/noto"
    remote_src: yes
  become: yes

- name: recache fonts
  when: ansible_os_family == "Debian"
  ansible.builtin.command:
    cmd: "fc-cache -fv"
