# MAC related
- name: Make sure Homebrew directories exists
  when: ansible_os_family == "Darwin"
  file: 
  path: /usr/local/*
  state: directory
  mode: 0775
  owner: root
  group: wheel
  recurse: yes
  become: yes

- name: download homebrew installation script
  when: ansible_os_family == "Darwin"
  get_url:
    url: https://raw.githubusercontent.com/homebrew/install/master/install
    dest: /tmp/install

- name: install homebrew
  shell: /usr/bin/ruby /tmp/install < /dev/null
    # 🎉 https://stackoverflow.com/a/39864317/503463


    # - name: download homebrew
    #   unarchive:
    #     src: 'https://github.com/homebrew/brew/archive/master.tar.gz'
    #     dest: /tmp/
    #     remote_src: yes

    # - name: move homebrew files to /usr/local
    #   synchronize: 
    #     src: /tmp/brew-master/
    #     dest: /usr/local/
    #   # delegate_to: "{{ inventory_hostname }}"
    #   become: yes

- name: set permissions for /usr/local/* #multiple users
  when: ansible_os_family == "Darwin"
  file: 
  path: '{{ item }}'
  mode: '0775'
  owner: '{{ username }}'
  group: wheel
  recurse: yes
  state: directory
  become: yes
  with_items: '{{ homebrew_paths }}'
  ignore_errors: yes


- name: fix acl permissions for multiple users
  when: ansible_os_family == "Darwin"
  become: yes
  command: 'chmod -r +a "group:admin allow list,add_file,search,delete,add_subdirectory,delete_child,readattr,writeattr,readextattr,writeextattr,readsecurity,file_inherit,directory_inherit" {{ item }}'
  args:
    warn: no
