# Linux related
- name: ensure apps directory exists
  when: ansible_os_family == "Debian"
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/Apps"
    state: directory
    mode: "0770"

- name: install required neovim packages
  when: ansible_os_family == "Debian"
  apt: name={{ item }} state=latest update_cache=yes
  loop: ["fuse", "libfuse2"]
  become: true

- name: install luarocks
  when: ansible_os_family == "Debian"
  ansible.builtin.shell: >
    curl -R -O http://www.lua.org/ftp/lua-5.3.5.tar.gz
    tar -zxf lua-5.3.5.tar.gz
    cd lua-5.3.5
    make linux test
    sudo make install
    rm -rf lua-5*
  become: true

- name: install neovim
  when: ansible_os_family == "Debian"
  ansible.builtin.shell: >
    rm -rf {{ ansible_env.HOME }}/Apps/nvim.appimage*;
    wget -P {{ ansible_env.HOME }}/Apps/ https://github.com/neovim/neovim/releases/download/v0.10.4/nvim-linux-arm64.appimage;
    mv {{ ansible_env.HOME }}/Apps/nvim-linux-arm64.appimage {{ ansible_env.HOME }}/Apps/nvim.appimage;
    chmod u+x {{ ansible_env.HOME }}/Apps/nvim.appimage

# MAC related
- name: install neovim
  when: ansible_os_family == "Darwin"
  become: true
  shell: brew install neovim

- name: ensure config directory exists
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.config"
    state: directory
    mode: "0770"

- name: copy neovim configurations
  git:
    repo: https://github.com/iamajoe/nvim
    dest: "{{ansible_env.HOME}}/.config/nvim"
    accept_hostkey: true
    force: true
  environment:
    GIT_TERMINAL_PROMPT: false
    GIT_SSL_NO_VERIFY: true
  # shell: git clone --depth 1 https://github.com/iamajoe/nvim ~/.config/nvim

- name: check if git remote upstream exists
  ansible.builtin.shell: |
    git remote | grep -q upstream
  args:
    chdir: "{{ansible_env.HOME}}/.config/nvim"
  register: git_origin_check
  ignore_errors: yes # Prevent failure if remote does not exist

- name: add git remote origin if not exists
  ansible.builtin.command: git remote add upstream git@github.com:iamajoe/nvim.git
  args:
    chdir: "{{ansible_env.HOME}}/.config/nvim"
  when: git_origin_check.rc != 0 # Only run if remote does not exist

