- name: install nvm
  become: no
  ansible.builtin.shell: >
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.1/install.sh | bash
  args:
    executable: /bin/bash
    chdir: "$HOME"
    creates: "$HOME/.nvm/nvm.sh"

- name: install node
  become: no
  shell: >
    . {{ ansible_env.HOME }}/.nvm/nvm.sh && nvm install {{ item }}
  args:
    executable: /bin/bash
    chdir: "{{ ansible_env.HOME }}"
    creates: "{{ ansible_env.HOME }}/.nvm/versions/{{ item }}"
  loop:
    - 23.6.1

- name: install node globals
  become: no
  shell: >
    npm install -g eslint_d typescript stylelint tree-sitter neovim
  args:
    executable: /bin/bash
