- name: copy npm configurations
  shell: printf 'prefix = {{ ansible_env.HOME  }}/npm' > .npmrc

- name: install nvm
  shell: curl https://raw.githubusercontent.com/creationix/nvm/master/install.sh | bash
  become: true

# Dependencies
- name: install npm distributed command-line tools
  npm:
    global: yes
    name: "{{ item }}"
    with_item:
      - typescript
      - prettier
