- name: ensure GRUB config has correct GFXMODE
  ansible.builtin.lineinfile:
    path: /etc/default/grub
    regexp: "^GRUB_GFXMODE="
    line: "GRUB_GFXMODE={{grub_resolution}}"
    state: present
  become: true
  when: grub_resolution is defined and grub_resolution | length > 0

- name: update GRUB configuration
  ansible.builtin.command: update-grub
  when: ansible_facts['os_family'] == "Debian"
  become: true
