# Linux related
- name: install rofi packages
  when: ansible_os_family == "Debian"
  apt: name={{ item }} state=latest update_cache=yes
  loop: ["rofi"]
  become: true

- name: ensure config rofi directory exists
  when: ansible_os_family == "Debian"
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.config/rofi"
    state: directory
    mode: "0755"

- name: copy rofi configurations
  when: ansible_os_family == "Debian"
  template: src=../templates/rofi dest="{{ ansible_env.HOME }}/.config/rofi/config.rasi"
  when: ansible_os_family == "Debian"
