- name: install required system packages
  when: ansible_os_family == "Debian"
  apt: name={{ item }} state=latest update_cache=yes
  # See: https://stackoverflow.com/a/37096534/100134
  loop: ["acl", "sshpass", "openssh-client", "openssh-server", "keychain"]
  become: true

- name: ensure .ssh directory exists
  ansible.builtin.file:
    path: "{{ansible_env.HOME}}/.ssh"
    state: directory
    mode: "0700"
  become_user: "{{ansible_user}}"

- name: copy SSH directory
  ansible.builtin.copy:
    src: "{{ssh_src_dir}}/"
    dest: "{{ansible_env.HOME}}/.ssh"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0600"
    directory_mode: "0700"
    remote_src: false
  become_user: "{{ansible_user}}"

- name: remove UseKeychain from SSH config
  when: ansible_os_family == "Debian" and ssh_src_dir is defined and ssh_src_dir | length > 0
  ansible.builtin.lineinfile:
    path: "{{ansible_env.HOME}}/.ssh/config"
    state: absent
    regexp: "^UseKeychain"
  become_user: "{{ansible_user}}"

- name: set correct permissions for SSH keys
  ansible.builtin.file:
    path: "{{ansible_env.HOME}}/.ssh/authorized_keys"
    mode: "0600"
  become_user: "{{ansible_user}}"

- name: ensure keychain is sourced
  when: ansible_os_family == "Debian"
  ansible.builtin.lineinfile:
    path: "{{ansible_env.HOME}}/.bashrc"
    line: "eval $(keychain --eval --agents ssh --quiet)"
    create: yes
