# Linux related
- name: install tmux (linux)
  when: ansible_os_family == "Debian"
  apt: name={{ item }} state=latest update_cache=yes
  loop: ["tmux"]
  become: true

# MAC related
- name: install tmux (mac)
  when: ansible_os_family == "Darwin"
  become: true
  shell: brew install tmux

- name: copy base tmux configuration
  template: src=../templates/tmux.conf dest="{{ ansible_env.HOME  }}/.tmux.conf"

- name: ensure tmux directory exists
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.config/terminal/tmux"
    state: directory
    mode: "0770"

- name: copy tmux configuration
  template: src=../templates/tmux/ dest="{{ ansible_env.HOME  }}/.config/terminal/tmux/"

- name: install tmux plugin manager
  shell: git clone --depth 1 https://github.com/tmux-plugins/tpm {{ ansible_env.HOME }}/.tmux/plugins/tpm
