- name: copy xfce resources
  when: ansible_os_family == "Debian"
  template: src=../templates/xfce/Xresources dest="{{ ansible_env.HOME  }}/.Xresources"

- name: copy xfce defaults
  when: ansible_os_family == "Debian"
  template: src=../templates/xfce/Xdefaults dest="{{ ansible_env.HOME  }}/.Xdefaults"

- name: copy keyboard default
  when: ansible_os_family == "Debian"
  template: src=../templates/xfce/default_keyboard dest="/etc/default/keyboard"

- name: copy xfce keyboard layout
  when: ansible_os_family == "Debian"
  template: src=../templates/xfce/xfconf/xfce-perchannel-xml/keyboard-layout.xml dest="{{ ansible_env.HOME  }}/.config/xfce4/xfconf/xfce-perchannel-xml/keyboard-layout.xml"

- name: copy xfce keyboard configurations
  when: ansible_os_family == "Debian"
  template: src=../templates/xfce/xfconf/xfce-perchannel-xml/xfce4-keyboard-shortcuts.xml dest="{{ ansible_env.HOME  }}/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-keyboard-shortcuts.xml"

- name: copy xfce panel configurations
  when: ansible_os_family == "Debian"
  template: src=../templates/xfce/xfconf/xfce-perchannel-xml/xfce4-panel.xml dest="{{ ansible_env.HOME  }}/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-panel.xml"

- name: install dracula theme
  when: ansible_os_family == "Debian"
  shell: git clone --depth 1 https://github.com/dracula/gtk.git {{ ansible_env.HOME }}/.themes/Dracula

- name: activate theme
  when: ansible_os_family == "Debian"
  become: true
  shell: gsettings set org.gnome.desktop.interface gtk-theme "Dracula" && gsettings set org.gnome.desktop.wm.preferences theme "Dracula"

- name: terminal template
  when: ansible_os_family == "Debian"
  shell: curl -o /usr/share/xfce4/terminal/colorschemes/Dracula.theme https://raw.githubusercontent.com/dracula/xfce4-terminal/master/Dracula.theme
