- name: copy xfce resources
  template: src=../templates/xfce/Xresources dest="{{ ansible_env.HOME  }}/.Xresources"

- name: copy xfce defaults
  template: src=../templates/xfce/Xdefaults dest="{{ ansible_env.HOME  }}/.Xdefaults"

- name: copy keyboard defaults
  template: src=../templates/xfce/keyboard_default dest="/etc/default/keyboard"

- name: reconfigure keyboard
  become: true
  shell: dpkg-reconfigure keyboard-configuration

- name: copy xfce keyboard layout
  template: src=../templates/xfce/xfconf/xfce-perchannel-xml/keyboard-layout.xml dest="{{ ansible_env.HOME  }}/.config/xfce4/xfconf/xfce-perchannel-xml/keyboard-layout.xml"

- name: copy xfce keyboard configurations
  template: src=../templates/xfce/xfconf/xfce-perchannel-xml/xfce4-keyboard-shortcuts.xml dest="{{ ansible_env.HOME  }}/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-keyboard-shortcuts.xml"

- name: copy xfce panel configurations
  template: src=../templates/xfce/xfconf/xfce-perchannel-xml/xfce4-panel.xml dest="{{ ansible_env.HOME  }}/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-panel.xml"

- name: install dracula theme
  become: true
  shell: git clone --depth 1 https://github.com/dracula/gtk.git ~/.themes/Dracula

- name: activate theme
  become: true
  shell: gsettings set org.gnome.desktop.interface gtk-theme "Dracula" && gsettings set org.gnome.desktop.wm.preferences theme "Dracula"

- name: terminal template
  become: true
  shell: curl -o /usr/share/xfce4/terminal/colorschemes/Dracula.theme https://raw.githubusercontent.com/dracula/xfce4-terminal/master/Dracula.theme
