- name: remove zig if it exists
  ansible.builtin.file:
    path: "/usr/local/zig"
    state: absent
  become: yes

- name: set zig download URL based on architecture
  set_fact:
    zig_url: >-
      {% if ansible_architecture == 'aarch64' %}
        https://ziglang.org/builds/zig-linux-aarch64-0.14.0.tar.xz
      {% elif ansible_architecture == 'armv7' %}
        https://ziglang.org/builds/zig-linux-armv7a-0.14.0.tar.xz
      {% else %}
        https://ziglang.org/builds/zig-linux-x86_64-0.14.0.tar.xz
      {% endif %}

- name: download zig
  ansible.builtin.get_url:
    url: "{{ zig_url }}"
    dest: "/tmp/zig_release.tar.gz"
    mode: "0644"

- name: ensure /usr/local/zig directory exists
  ansible.builtin.file:
    path: "/usr/local/zig"
    state: directory
    mode: "0755"
  become: yes # Run as root if needed

- name: extract and install zig
  ansible.builtin.unarchive:
    src: "/tmp/zig_release.tar.gz"
    dest: "/usr/local/bin"
    remote_src: yes
    extra_opts: [--strip-components=1] # Ensures correct structure
  become: yes
