[language-server.vscode-eslint-language-server]
command = "vscode-eslint-language-server"
args = ["--stdio"]

[[language]]
name = "javascript"
auto-format = true
language-servers = [
  "typescript-language-server",
  { name = "vscode-eslint-language-server", only-features = ["diagnostics", "code-action"] }
]
formatter = { command = "prettier", args = ["--stdin-filepath", "%{buffer_name}"] }

[[language]]
name = "typescript"
auto-format = true
language-servers = [
  "typescript-language-server",
  { name = "vscode-eslint-language-server", only-features = ["diagnostics", "code-action"] }
]
formatter = { command = "prettier", args = ["--stdin-filepath", "%{buffer_name}"] }

[[language]]
name = "jsx"
auto-format = true
language-servers = [
  "typescript-language-server",
  { name = "vscode-eslint-language-server", only-features = ["diagnostics", "code-action"] }
]
formatter = { command = "prettier", args = ["--stdin-filepath", "%{buffer_name}"] }

[[language]]
name = "tsx"
auto-format = true
language-servers = [
  "typescript-language-server",
  { name = "vscode-eslint-language-server", only-features = ["diagnostics", "code-action"] }
]
formatter = { command = "prettier", args = ["--stdin-filepath", "%{buffer_name}"] }

