events {
    worker_connections 1024;
}

http {
    resolver 127.0.0.11 valid=10s;

    map $http_upgrade $connection_upgrade {
        default upgrade;
        '' close;
    }

    server {
        listen 80;

        client_max_body_size 2G;
        underscores_in_headers on;

        set $appflowy_cloud_backend "http://appflowy_cloud:8000";
        set $gotrue_backend "http://appflowy_gotrue:9999";
        set $admin_frontend_backend "http://appflowy_admin_frontend:3000";
        set $appflowy_web_backend "http://appflowy_web:80";
        set $minio_backend "http://appflowy-minio:9001";
        set $minio_api_backend "http://appflowy-minio:9000";
        set $minio_internal_host "appflowy-minio:9000";

        # GoTrue
        location /gotrue/ {
            proxy_pass $gotrue_backend;
            rewrite ^/gotrue(/.*)$ $1 break;

            proxy_set_header Host $http_host;
            proxy_pass_request_headers on;
        }

        # WebSocket
        location /ws {
            proxy_pass $appflowy_cloud_backend;

            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "Upgrade";
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_read_timeout 86400s;
        }

        # AppFlowy Cloud API
        location /api {
            proxy_pass $appflowy_cloud_backend;

            proxy_set_header X-Request-Id $request_id;
            proxy_set_header Host $http_host;

            proxy_request_buffering off;
        }

        # MinIO Web UI
        location /appflowy_minio/ {
            proxy_pass $minio_backend;

            rewrite ^/appflowy_minio/(.*) /$1 break;

            proxy_set_header Host $http_host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";

            proxy_connect_timeout 300s;
        }

        # MinIO API / presigned URLs
        location /appflowy_minio-api/ {
            proxy_pass $minio_api_backend;

            rewrite ^/appflowy_minio-api/(.*) /$1 break;

            proxy_set_header Host $minio_internal_host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            proxy_connect_timeout 300s;
            proxy_read_timeout 600s;
            proxy_send_timeout 600s;

            proxy_request_buffering off;
            proxy_http_version 1.1;
            proxy_set_header Connection "";

            client_max_body_size 0;
        }

        # Admin frontend
        location /console {
            proxy_pass $admin_frontend_backend;

            proxy_set_header X-Forwarded-Host $http_host;
            proxy_set_header Host $http_host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Scheme $scheme;

            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }

        # AppFlowy Web
        location / {
            proxy_pass $appflowy_web_backend;

            proxy_set_header X-Scheme $scheme;
            proxy_set_header Host $host;
        }
    }
}
