#!/bin/sh

export XDG_SESSION_TYPE=x11
export XDG_CURRENT_DESKTOP=qtile
export XDG_SESSION_DESKTOP=qtile
export DESKTOP_SESSION=qtile

if [ -z "$DBUS_SESSION_BUS_ADDRESS" ]; then
eval "$(dbus-launch --exit-with-session --sh-syntax)"
fi

systemctl --user import-environment \
DISPLAY \
XAUTHORITY \
XDG_CURRENT_DESKTOP \
XDG_SESSION_DESKTOP \
XDG_SESSION_TYPE \
DESKTOP_SESSION

if command -v dbus-update-activation-environment >/dev/null 2>&1; then
dbus-update-activation-environment --systemd \
DISPLAY \
XAUTHORITY \
XDG_CURRENT_DESKTOP \
XDG_SESSION_DESKTOP \
XDG_SESSION_TYPE \
DESKTOP_SESSION
fi

eval "$(gnome-keyring-daemon --start --components=secrets,ssh,pkcs11)"
export SSH_AUTH_SOCK

# Change resolution
# xrandr --output DP-2 --mode 2560x1440 --rate 60
# xrandr --output DP-2 --mode 1920x1080 --rate 60

# Load Xresources if present
[ -f "$HOME/.Xresources" ] && xrdb -merge "$HOME/.Xresources"

lxqt-policykit-agent &

# changes left-right on the kensington mouse
xinput set-button-map "Kensington Expert Wireless TB Mouse" 3 8 1 4 5 6 7 2

# run the opencode web detached so i can access from outside
# opencode web --port 4096 --hostname "0.0.0.0" &

exec qtile start
