# Let new devices join our zigbee network
# TODO: should be removed after all setup
permit_join: true
# Docker-Compose makes the MQTT-Server available using "mqtt" hostname
# TODO: dont forget to change the ip
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://192.168.0.128:1883
# Zigbee Adapter path
serial:
  port: /dev/ttyUSB0
# Enable the Zigbee2MQTT frontend
frontend:
  port: 8099
# Let Zigbee2MQTT generate a new network key on first start
advanced:
  pan_id: GENERATE
  ext_pan_id: GENERATE
  network_key: GENERATE
  channel: 15
# Allow Zigbee2MQTT to auto add devices to HA
homeassistant: true
