# This is the tmux dracula theme file
# Dracula theme colors in use, with the following colors:
# background   darkest grey   colour17    #282a36 (mode line itself)
# current line dark grey      colour59    #44475a
# selection    dark grey      colour59    #44475a
# foreground   cream white    colour231   #f8f8f2
# comment      dark blue      colour61    #6272a4
# cyan         cyan           colour117   #8be9fd
# green        green          colour84    #50fa7b
# orange       orange         colour215   #ffb86c
# pink         pink           colour212   #ff79ca
# purple       purple         colour141   #bd93f9
# red          red            colour203   #ff5555
# yellow       yellow         colour228   #f1fa8c

# default inactive statusbar colors
# Dracula theme
set-option -g status-bg "#282a36"  # Background
set-option -g status-fg "#f8f8f2"  # Foreground
# set-option -g status-attr default

# pane border
# set-option -g pane-border-fg colour228
# set-option -g pane-active-border-fg colour203

# message text
# set-option -g message-bg "#ff5555"  # Red
# set-option -g message-fg "#282a36"  # Background
# set-option -g message-attr bright

# pane number display
set-option -g display-panes-active-colour blue
set-option -g display-panes-colour brightred

# Selected window
set-option -g window-status-current-format "#[bg=#50fa7b,fg=#44475a] #I:#W "
# Inactive window
set-option -g window-status-format "#[bg=#282a36,fg=#66675a] #I:#W "

# Remove padding at the left hand side
set -g status-left ""
# Show a clock at the right hand side
set -g status-right "#[bg=#ff79ca,fg=#44475a] #(cd #{pane_current_path}; git rev-parse --abbrev-ref HEAD) #[bg=#6272a4,fg=#f8f8f2] %Y-%m-%d %H:%M "

