- name: project_example
  hosts: "{{target}}"
  tasks:
    # - name: set org work folder
    #   shell: mkdir -p {{ ansible_env.HOME  }}/work/src/github.com/your_org
    #   become: true
    #
    # - name: clone your_project_name
    #   git:
    #     repo: git@github.com:your_org/your_project_name.git
    #     dest: "{{ansible_env.HOME}}/work/src/github.com/your_org/your_project_name"
    #     version: main
    #     accept_hostkey: true
    #     force: true
    #   environment:
    #     GIT_TERMINAL_PROMPT: false
    #     GIT_SSL_NO_VERIFY: true
    #     GIT_SSH_COMMAND: "ssh -i {{ansible_env.HOME}}/.ssh/id_rsa -o StrictHostKeyChecking=no"
