[user]
  name = {{git_user_fullname}}
  email = {{git_user_email}}
[init]
  defaultBranch = main
[core]
  editor = /home/{{ansible_user}}/Apps/nvim.appimage
[color]
  ui = auto
[pull]
  rebase = false
[pager]
  branch = false
