# REF: https://github.com/LGUG2Z/helix-vim/blob/master/config.toml
# REF: https://raphgl.github.io/blog/helix-tutorial.html
#
# CHEATSHEET: PANELS
# <space> : Panels (file picker, buffer picker, perform code action...)
# <g>     : Goto (column, line, reference, buffer...)
# <m>     : Match (surround, inside, around...)
# <z>     : View mode
# "       : Registers
#
# CHEATSHEET: SHORTCUTS
# ctrl+f : Multi cursor on selection
# ctrl+j : Join lines
# gn     : Next buffer
# gp     : Prev buffer
#
# CHEATSHEET: NAVIGATION
# gh : beginning of line
# gl : end of line

theme = "catppuccin_mocha_mod"

[editor]
scrolloff = 8
line-number = "relative"
cursorline = true
rulers = [90]
# color-modes = true
bufferline = "multiple"
# popup-border = "all" # TODO: what is this for?
completion-replace = true
trim-trailing-whitespace = true

[editor.statusline]
left = ["spinner", "mode", "spacer", "version-control", "file-absolute-path","read-only-indicator", "file-modification-indicator"]
right = ["diagnostics", "workspace-diagnostics", "selections", "position", "total-line-numbers"]

[editor.cursor-shape]
insert = "bar"
select = "underline"

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true
character = "▏"

[editor.whitespace.render]
tab = "all"

[editor.lsp]
enable = true
auto-signature-help = true

[keys.normal]
# Navigation
0 = "goto_line_start"
"$" = "goto_line_end"
G = "goto_file_end"
"{" = ["goto_prev_paragraph", "collapse_selection"]
"}" = ["goto_next_paragraph", "collapse_selection"]

V = ["select_mode", "extend_to_line_bounds"]
# C = ["extend_to_line_end", "yank_main_selection_to_clipboard", "delete_selection", "insert_mode"]
D = ["extend_to_line_end", "yank_main_selection_to_clipboard", "delete_selection"]

# Clipboards over registers ye ye
p = ["replace_selections_with_clipboard", "collapse_selection"]
P = ["paste_clipboard_before", "collapse_selection"]
y = ["yank_main_selection_to_clipboard", "flip_selections", "collapse_selection"]
Y = ["extend_to_line_end", "yank_main_selection_to_clipboard", "goto_line_start", "collapse_selection", "normal_mode"]

# Modifications
C-j = "join_selections"

# Selection
C-h = "select_prev_sibling"
C-n = "shrink_selection"
C-k = "expand_selection"
C-l = "select_next_sibling"

# Multi cursor
C-f = ["search_selection", "extend_search_next"]

# Undoing the 'd' + motion commands restores the selection which is annoying
# u = ["undo", "collapse_selection"]

# Misc
# Escape the madness! No more fighting with the cursor! Or with multiple cursors!
esc = ["collapse_selection", "keep_primary_selection"]
K = "hover"

[keys.normal.space]
# o = ":sh tmux new-window -n fx '~/.config/helix/yazi-picker.sh open'"
# Open a file using yazi tree structure
o = [
  ':sh rm -f /tmp/unique-file',
  ':insert-output yazi "%{buffer_name}" --chooser-file=/tmp/unique-file',
  ':sh printf "\x1b[?1049h\x1b[?2004h" > /dev/tty',
  ':open %sh{cat /tmp/unique-file}',
  ':redraw',
]
f = ["file_picker_in_current_directory"]
F = [":format"]
W = ":toggle soft-wrap.enable"

[keys.select]
# Navigation
0 = "goto_line_start"
"$" = "goto_line_end"
G = "goto_file_end"

# Modifications
C-j = "join_selections"
# u = ["switch_to_lowercase", "collapse_selection", "normal_mode"]
# U = ["switch_to_uppercase", "collapse_selection", "normal_mode"]

# Clipboards over registers ye ye
d = ["yank_main_selection_to_clipboard", "delete_selection"]
y = ["yank_main_selection_to_clipboard", "normal_mode", "flip_selections", "collapse_selection"]
Y = ["extend_to_line_bounds", "yank_main_selection_to_clipboard", "goto_line_start", "collapse_selection", "normal_mode"]
p = "replace_selections_with_clipboard" # No life without this
P = "paste_clipboard_before"

# Multi cursor
C-f = ["search_selection", "extend_search_next"]

# Escape the madness! No more fighting with the cursor! Or with multiple cursors!
esc = ["collapse_selection", "keep_primary_selection", "normal_mode"]

[keys.insert]
"C-h" = "signature_help"

# TODO: no custom comment keyword highlights (DEPRECATED, STUDY, IMPORTANT)
