onboarding = false

[ui.toast]
delivery = "system"

[ui]
show_agent_labels_on_pane_borders = true
pane_gaps = false
pane_borders = true
sidebar_width = 16
sidebar_min_width = 16
sidebar_max_width = 22

[ui.sidebar.agents]
row_gap = 0
rows = [
  ["state_icon", "agent"],
]

[ui.sidebar.spaces]
row_gap = 0
rows = [
  ["state_icon", "workspace", "git_status"],
]

[experimental]
pane_history = false

[keys]
prefix = "ctrl+a"
split_horizontal = "prefix+s"
split_vertical = "prefix+a"
navigate_workspace_up = "k"
navigate_workspace_down = "j"

[[keys.command]]
key = "prefix+g"
type = "popup"
command = "lazygit"
description = "LazyGit"
width = "90%"
height = "90%"
