# List of plugins
# set -g @plugin 'tmux-plugins/tpm'
# set -g @plugin 'tmux-plugins/tmux-sensible'
# set -g @plugin 'tmux-plugins/tmux-resurrect' # restores state on restart
# set -g @plugin 'tmux-plugins/tmux-continuum' # keeps saving state
# set -g @plugin 'christoomey/vim-tmux-navigator'
# set -g @plugin 'tmux-plugins/tmux-yank'

# Set bind key
unbind C-b
# set -g prefix C-Space
# bind C-Space send-prefix
set -g prefix C-A
bind C-A send-prefix

# enter copy mode
bind r copy-mode

# split windows like vim
bind s split-window -v -c "#{pane_current_path}"
bind a split-window -h -c "#{pane_current_path}"

# window numbering starts at 1
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# set mouse
# set -g mouse on

# look good
set -g default-terminal "xterm-256color"
# set -g default-terminal "tmux-256color"
set-option -sa terminal-overrides ',XXX:RGB'

# no time between C-a and command
set -s escape-time 1

# set scrollback history to 10000 (10k)
set -g history-limit 10000

# visual notification of activity in other windows
setw -g monitor-activity on
set -g visual-activity on

# Resize pane
# bind j resize-pane -D 15
# bind k resize-pane -U 15
# bind l resize-pane -L 15
# bind h resize-pane -R 15

# change panel
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Shift Alt vim keys to switch windows
bind -n M-H previous-window
bind -n M-L next-window

# set-window-option -g mode-keys vi
# bind-key -T copy-mode-vi v send-keys -X begin-selection
# bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
# bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# Display popups
bind g display-popup \
  -d "#{pane_current_path}" \
  -w 90% \
  -h 90% \
  -E "lazygit"

bind C-t display-popup \
  -d "#{pane_current_path}" \
  -w 75% \
  -h 75% \
  -E "zsh"

bind u display-popup -E 'tmux choose-tree -F "#{?pane_format,#[fg=colour11]#{pane_current_command} #[fg=colour172]#{pane_title},#{?window_format,#[fg=colour40]#{window_name}#{window_flags}#{?#{==:#{window_panes},1}, #{?#{!=:#{window_name},#{pane_current_command}},#[fg=colour11]#{pane_current_command} ,}#[fg=colour172]#{pane_title},},#[fg=colour105]#{?session_grouped, (group #{session_group}: #{session_group_list}),}#{?session_attached,(attached),#[fg=colour9](unattached)}}}"'

# Display menus
bind m display-menu -T "#[align=centre]Menu" -x C -y C \
  "Change session"                     l 'choose-tree -F "#{?pane_format,#[fg=colour11]#{pane_current_command} #[fg=colour172]#{pane_title},#{?window_format,#[fg=colour40]#{window_name}#{window_flags}#{?#{==:#{window_panes},1}, #{?#{!=:#{window_name},#{pane_current_command}},#[fg=colour11]#{pane_current_command} ,}#[fg=colour172]#{pane_title},},#[fg=colour105]#{?session_grouped, (group #{session_group}: #{session_group_list}),}#{?session_attached,(attached),#[fg=colour9](unattached)}}}"' \
  "New session"                        n "command-prompt -p \"New session:\" \"new-session -A -s '%%'\"" \
  "Kill session"                       x "kill-session" \
  "Kill other session(s)"              X "kill-session -a" \
  "" \
  "Rename window"                      r "command-prompt -I \"#W\" \"rename-window -- '%%'\"" \
  "Swap pane up"                       "<" "swap-pane -U" \
  "Swap pane down"                     ">" "swap-pane -D" \
  "Break pane"                         t break-pane \
  "Join pane"                          j "choose-window 'join-pane -h -s \"%%\"'" \
  "" \
  "Exit"                               q  ""

# setup the theme
# run-shell "tmux source-file ~/.tmux.\${TMUX_THEME:-default}.theme"
run-shell "tmux source-file $HOME/.config/tmux/catppuccin.theme"

# setup session saves between restarts
# set -g @continuum-restore 'on'
# set -g @continuum-boot 'on'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
# run '~/.tmux/plugins/tpm/tpm'
