{ config, pkgs, ... }:

{
  # RustDesk remote desktop package
  home.packages = with pkgs; [
    rustdesk  # Remote desktop client & server

    # Helper script to show RustDesk local network connection info
    (pkgs.writeShellScriptBin "rustdesk-local-info" ''
      echo "=== RustDesk Local Network Connection Info ==="
      echo ""

      # Get RustDesk ID
      CONFIG_DIR="$HOME/.config/rustdesk"
      CONFIG_FILE="$CONFIG_DIR/RustDesk2.toml"

      if [ -f "$CONFIG_FILE" ]; then
        # Try to extract ID from config
        RUSTDESK_ID=$(grep -oP '(?<=^id = ")[^"]+' "$CONFIG_FILE" 2>/dev/null || echo "")
        if [ -n "$RUSTDESK_ID" ]; then
          echo "🆔 RustDesk ID: $RUSTDESK_ID"
        else
          echo "⚠️ RustDesk ID not found in config (may not be generated yet)"
        fi
      else
        echo "⚠️ RustDesk config not found - run RustDesk first to generate ID"
      fi

      echo ""
      echo "🌐 Local IP Addresses:"
      ip -4 addr show | grep -oP '(?<=inet\s)\d+(\.\d+){3}' | grep -v 127.0.0.1
      echo ""
      echo "🔌 Connection Port: 21118"
      echo "   Use the password set with: rustdesk --password your-password"
      echo ""
      echo "💡 RustDesk is configured for LOCAL NETWORK ONLY (no internet relay)"
      echo "   ID regenerates on every reboot for security"
      echo ""
    '')
  ];

  # RustDesk setup script (run on each boot to regenerate ID and apply settings)
  home.file.".local/bin/rustdesk-setup.sh" = {
    executable = true;
    text = ''
      #!/usr/bin/env bash
      
      CONFIG_DIR="$HOME/.config/rustdesk"
      CONFIG_FILE="$CONFIG_DIR/RustDesk2.toml"
      
      # Create config directory if it doesn't exist
      mkdir -p "$CONFIG_DIR"
      
      # Remove old config and ID to force regeneration
      rm -f "$CONFIG_FILE" 2>/dev/null
      rm -f "$CONFIG_DIR"/*.db* 2>/dev/null
      rm -f "$CONFIG_DIR"/id 2>/dev/null
      
      # Create new config with local network only settings
      cat > "$CONFIG_FILE" << 'EOF'
[options]
# Disable relay servers to force local network only
relay-server = ""
rendezvous-server = ""

# Enable direct IP connections (local network)
direct-server = true
direct-access-port = "21118"

# Network settings
allow-lan-discovery = true

# ID will be auto-generated by RustDesk
EOF
      
      echo "RustDesk configured for local network only (IP-restricted). ID will be regenerated."
    '';
  };
}
