{ config, pkgs, ... }:

{
  # RustDesk remote desktop package and helper scripts
  home.packages = with pkgs; [
    rustdesk  # Remote desktop client & server

    # Helper script to set RustDesk password
    (pkgs.writeShellScriptBin "rustdesk-set-password" ''
      #!/usr/bin/env bash

      PASSWORD_FILE="$HOME/.config/rustdesk/.p"

      # Create config directory if it doesn't exist
      mkdir -p "$HOME/.config/rustdesk"

      echo "Enter RustDesk password:"
      read -s password

      if [ -z "$password" ]; then
        echo "Error: Password cannot be empty"
        exit 1
      fi

      echo "$password" > "$PASSWORD_FILE"
      chmod 600 "$PASSWORD_FILE"

      echo ""
      echo "✅ Password saved! It will be applied on next reboot or when you run:"
      echo "   ~/.local/bin/rustdesk-setup.sh && pkill -9 rustdesk && rustdesk --silent &"
    '')

    # Helper script to show RustDesk local network connection info
    (pkgs.writeShellScriptBin "rustdesk-local-info" ''
      echo "=== RustDesk Local Network Connection Info ==="
      echo ""

      # Get RustDesk ID
      CONFIG_DIR="$HOME/.config/rustdesk"
      CONFIG_FILE="$CONFIG_DIR/RustDesk2.toml"

      if [ -f "$CONFIG_FILE" ]; then
        # Try to extract ID from config
        RUSTDESK_ID=$(grep -oP '(?<=^id = ")[^"]+' "$CONFIG_FILE" 2>/dev/null || echo "")
        if [ -n "$RUSTDESK_ID" ]; then
          echo "🆔 RustDesk ID: $RUSTDESK_ID"
        else
          echo "⚠️ RustDesk ID not found in config (may not be generated yet)"
        fi
      else
        echo "⚠️ RustDesk config not found - run RustDesk first to generate ID"
      fi

      # Check if password is set
      if [ -f "$HOME/.config/rustdesk/.rustdesk_password" ]; then
        echo "🔑 Password: ✅ Set (stored in ~/.config/rustdesk/.rustdesk_password)"
      else
        echo "🔑 Password: ❌ Not set - run: rustdesk-set-password"
      fi

      echo ""
      echo "🌐 Local IP Addresses:"
      ip -4 addr show | grep -oP '(?<=inet\s)\d+(\.\d+){3}' | grep -v 127.0.0.1
      echo ""
      echo "🔌 Connection Port: 21118"
    '')
  ];

  # RustDesk setup script (run on each boot to regenerate ID and apply settings)
  home.file.".local/bin/rustdesk-setup.sh" = {
    executable = true;
    text = ''
      #!/usr/bin/env bash

      CONFIG_DIR="$HOME/.config/rustdesk"
      CONFIG_FILE="$CONFIG_DIR/RustDesk2.toml"
      PASSWORD_FILE="$CONFIG_DIR/.p"

      # Create config directory if it doesn't exist
      mkdir -p "$CONFIG_DIR"

      # Remove old config and ID to force regeneration
      rm -f "$CONFIG_FILE" 2>/dev/null
      rm -f "$CONFIG_DIR"/*.db* 2>/dev/null
      rm -f "$CONFIG_DIR"/id 2>/dev/null

      # Read password from file if it exists
      RUSTDESK_PASSWORD=""
      if [ -f "$PASSWORD_FILE" ]; then
        RUSTDESK_PASSWORD=$(cat "$PASSWORD_FILE")
      fi

      # Create new config with local network only settings
      cat > "$CONFIG_FILE" << EOF
[options]
# Disable relay servers to force local network only
relay-server = ""
rendezvous-server = ""

# Enable direct IP connections (local network)
direct-server = true
direct-access-port = "21118"

# Network settings
allow-lan-discovery = true

# Password (if set)
password = "$RUSTDESK_PASSWORD"

# ID will be auto-generated by RustDesk
EOF

      if [ -n "$RUSTDESK_PASSWORD" ]; then
        echo "RustDesk configured for local network only with password."
      else
        echo "RustDesk configured for local network only. No password set."
        echo "To set a password, run: rustdesk-set-password"
      fi
    '';
  };
}
