- name: dev
  hosts: local
  tasks:
    - include_tasks: ../tasks/homebrew.yml
    - include_tasks: ../tasks/basic.yml
    - include_tasks: ../tasks/basicdev.yml
    - include_tasks: ../tasks/zsh.yml
    - include_tasks: ../tasks/vim.yml
    - include_tasks: ../tasks/tmux.yml
    - include_tasks: ../tasks/docker.yml
    - include_tasks: ../tasks/go.yml
    - include_tasks: ../tasks/node.yml
