- name: dev
  hosts: local
  tasks:
    - include_tasks: ../tasks/homebrew.yml
    - include_tasks: ../tasks/basic.yml
    - include_tasks: ../tasks/dev.yml
    - include_tasks: ../tasks/alacritty.yml
    - include_tasks: ../tasks/fish.yml
    - include_tasks: ../tasks/docker.yml
    - include_tasks: ../tasks/xfce.yml
    - include_tasks: ../tasks/audio.yml

    # create necessary folders
    - name: set github work folder
      shell: mkdir -p {{ ansible_env.HOME  }}/work/src/github.com/iamajoe
      become: true

    - name: set local work folder
      shell: mkdir -p {{ ansible_env.HOME  }}/work/src/local
      become: true

    # install go
    - import_role:
        name: abdennour.golang
        become: yes
        vars:
          golang_versoin: "1.21"
          golang_users:
            - "{{ ansible_ssh_user }}"

    # install node
    - name: Install nodejs
      hosts: all
      tasks:
        - name: Install nvm
          become: no
          ansible.builtin.shell: >
            curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.39.5/install.sh | bash
          args:
            executable: /bin/bash
            chdir: "$HOME"
            creates: "$HOME/.nvm/nvm.sh"

        - name: Install node
          become: no
          shell: >
            . {{ ansible_env.HOME }}/.nvm/nvm.sh && nvm install {{ item }}
          args:
            executable: /bin/bash
            chdir: "{{ ansible_env.HOME }}"
            creates: "{{ ansible_env.HOME }}/.nvm/versions/{{ item }}"
          loop:
            - 20.10.0

    # bluetooth
    - name: install bluetooth
      when: ansible_os_family == "Debian"
      apt: name={{ item }} state=latest update_cache=yes
      loop:
        [
          "bluez",
          "bluez-tools",
          "blueman"
        ]
      become: true
