- name: devlinux
  hosts: local
  tasks:
    - import_playbook: general.yml
    - import_playbook: generallinux.yml
    - import_playbook: dev.yml
    
    ##########################
    # NODE RELATED

    - name: add nodejs apt key
      apt_key:
        url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
        state: present
      become: true
    
    - name: add nodejs 18.x ppa for apt repo
      apt_repository:
        repo: deb https://deb.nodesource.com/node_18.x bionic main
        update_cache: true
      become: true

    - name: install nodejs
      apt:
        name: nodejs
        state: present
        update_cache: true

    - name: install npm distributed command-line tools
      npm:
        global: yes
        name: "{{ item }}"
      with_item:
        - typescript
