- name: devmac
  hosts: local
  tasks:
    - import_playbook: general.yml
    - import_playbook: generalmac.yml
    - import_playbook: dev.yml
    
    - name: install nodejs
      shell: brew install node@18
      become: true

    - name: install npm distributed command-line tools
      npm:
        global: yes
        name: "{{ item }}"
      with_item:
        - typescript
