- name: devvm
  hosts: "{{target}}"
  tasks:
    - include_tasks: ../tasks/core.yml
    - include_tasks: ../tasks/git.yml
    - include_tasks: ../tasks/terminal.yml
    - include_tasks: ../tasks/tmux.yml
    - include_tasks: ../tasks/neovim.yml
    - include_tasks: ../tasks/docker.yml
    - include_tasks: ../tasks/go.yml
    - include_tasks: ../tasks/zig.yml
    - include_tasks: ../tasks/node.yml
    - include_tasks: ../tasks/font.yml
    - include_tasks: ../tasks/i3.yml
    # - include_tasks: ../tasks/rofi.yml
    # - include_tasks: ../tasks/hyprland.yml
    - include_tasks: ../tasks/alacritty.yml
    # - include_tasks: ../tasks/vmware.yml
    - include_tasks: ../tasks/browser.yml

    # create necessary folders
    - name: set local work folder
      shell: mkdir -p {{ ansible_env.HOME  }}/work/src/local
      become_user: "{{ansible_user}}"
